repos:
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: uv run mypy --package gower_metric --package tests --package examples --package comparison
        language: system
        pass_filenames: false

  - repo: https://github.com/pypa/pip-audit
    rev: v2.10.0
    hooks:
      - id: pip-audit
        args: [
          --vulnerability-service, "pypi",
          --cache-dir, ".pip_audit_cache",
          --ignore-vuln, "GHSA-38jv-5279-wg99", # Decompression-bomb safeguards bypassed when following HTTP redirects (streaming API)
          --ignore-vuln, "GHSA-qmgc-5h2g-mvrw", # Time-of-Check-Time-of-Use (TOCTOU) Symlink Vulnerability in SoftFileLock
        ]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.10
    hooks:
      - id: ruff
        args: [--fix, --unsafe-fixes]
      - id: ruff-format