[mypy]

warn_return_any = True
strict_optional = True
check_untyped_defs = True
no_implicit_optional = True
disallow_any_unimported = True
disallow_untyped_defs = True
show_error_codes = True
warn_unused_ignores = True
ignore_missing_imports = True