[env_run_base]
description = "Run tests"
requires = ["tox>=4"]
deps = ["pytest", "pytest-cov", "check-manifest", "rpy2", "setuptools", "scipy", "scikit-learn", "numpy", "pandas", "mypy", "tqdm", "pydantic", "openpyxl"]
allowlist_externals = ["pytest", "python", "check-manifest"]
commands = [
    ["pytest", "--cov", "--cov-report=term-missing", "{posargs:tests}"],
    ["python", "-m", "build"],
    ["check-manifest"],
    ]

[env.py310]
description = "Run tests with Python 3.10"
base_python = ["python3.10"]

[env.py311]
description = "Run tests with Python 3.11" 
base_python = ["python3.11"]

[env.py312]
description = "Run tests with Python 3.12"
base_python = ["python3.12"]

[env.py313]
description = "Run tests with Python 3.13"
base_python = ["python3.13"]

[env.py314]
description = "Run tests with Python 3.14"
base_python = ["python3.14"]

[env.py]
description = "Run tests with current Python"