"""Gower metric C++ core (nanobind bindings)"""

from collections.abc import Mapping, Sequence
from typing import Annotated

import numpy
from numpy.typing import NDArray


class CppConfigData:
    def __init__(self) -> None: ...

    @property
    def feature_types(self) -> list[str]: ...

    @feature_types.setter
    def feature_types(self, arg: Sequence[str], /) -> None: ...

    @property
    def feature_weights(self) -> Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C', device='cpu', writable=False)]: ...

    @feature_weights.setter
    def feature_weights(self, arg: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C', device='cpu', writable=False)], /) -> None: ...

    @property
    def ranges(self) -> Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C', device='cpu', writable=False)]: ...

    @ranges.setter
    def ranges(self, arg: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C', device='cpu', writable=False)], /) -> None: ...

    @property
    def bandwidths(self) -> Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C', device='cpu', writable=False)]: ...

    @bandwidths.setter
    def bandwidths(self, arg: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C', device='cpu', writable=False)], /) -> None: ...

    @property
    def missing_strategy(self) -> str: ...

    @missing_strategy.setter
    def missing_strategy(self, arg: str, /) -> None: ...

    @property
    def scale_method(self) -> str: ...

    @scale_method.setter
    def scale_method(self, arg: str, /) -> None: ...

    @property
    def categorical_ordinal_calculation_type(self) -> str: ...

    @categorical_ordinal_calculation_type.setter
    def categorical_ordinal_calculation_type(self, arg: str, /) -> None: ...

    @property
    def conditional_distances(self) -> bool: ...

    @conditional_distances.setter
    def conditional_distances(self, arg: bool, /) -> None: ...

    @property
    def conditional_distances_threshold_coeff(self) -> int: ...

    @conditional_distances_threshold_coeff.setter
    def conditional_distances_threshold_coeff(self, arg: int, /) -> None: ...

    @property
    def discretization(self) -> str: ...

    @discretization.setter
    def discretization(self, arg: str, /) -> None: ...

    @property
    def silverman_constant(self) -> float: ...

    @silverman_constant.setter
    def silverman_constant(self, arg: float, /) -> None: ...

    @property
    def k_neighbors(self) -> int | None: ...

    @k_neighbors.setter
    def k_neighbors(self, arg: int | None) -> None: ...

    @property
    def handle_unseen_binary_asymmetric(self) -> str: ...

    @handle_unseen_binary_asymmetric.setter
    def handle_unseen_binary_asymmetric(self, arg: str, /) -> None: ...

    @property
    def handle_unseen_binary_symmetric(self) -> str: ...

    @handle_unseen_binary_symmetric.setter
    def handle_unseen_binary_symmetric(self, arg: str, /) -> None: ...

    @property
    def handle_unseen_categorical_nominal(self) -> str: ...

    @handle_unseen_categorical_nominal.setter
    def handle_unseen_categorical_nominal(self, arg: str, /) -> None: ...

    @property
    def handle_unseen_categorical_ordinal(self) -> str: ...

    @handle_unseen_categorical_ordinal.setter
    def handle_unseen_categorical_ordinal(self, arg: str, /) -> None: ...

    @property
    def out_of_range(self) -> str: ...

    @out_of_range.setter
    def out_of_range(self, arg: str, /) -> None: ...

    @property
    def skip_out_of_range_validation(self) -> bool: ...

    @skip_out_of_range_validation.setter
    def skip_out_of_range_validation(self, arg: bool, /) -> None: ...

    @property
    def categorical_ordinal_values_order(self) -> dict[int, list[str]]: ...

    @categorical_ordinal_values_order.setter
    def categorical_ordinal_values_order(self, arg: Mapping[int, Sequence[str]], /) -> None: ...

    @property
    def binary_asymmetric_value_order(self) -> dict[int, list[str]]: ...

    @binary_asymmetric_value_order.setter
    def binary_asymmetric_value_order(self, arg: Mapping[int, Sequence[str]], /) -> None: ...

    @property
    def binary_symmetric_value_order(self) -> dict[int, list[str]]: ...

    @binary_symmetric_value_order.setter
    def binary_symmetric_value_order(self, arg: Mapping[int, Sequence[str]], /) -> None: ...

    @property
    def ordinal_counts(self) -> dict[int, list[float]]: ...

    @ordinal_counts.setter
    def ordinal_counts(self, arg: Mapping[int, Sequence[float]], /) -> None: ...

class CppConfig:
    def __init__(self) -> None: ...

    def configure_arguments(self, data: CppConfigData) -> None:
        """Populate the config from a ConfigData."""

    @property
    def n_features(self) -> int: ...

    @property
    def feature_weights(self) -> list[float]: ...

    @property
    def ranges(self) -> list[float]: ...

    @property
    def bandwidths(self) -> list[float]: ...

    def calculate_distance(self, x: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C', device='cpu', writable=False)], y: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C', device='cpu', writable=False)]) -> float:
        """Gower distance between two 1-D feature vectors."""

    def calculate_matrix(self, data: Annotated[NDArray[numpy.float64], dict(shape=(None, None), order='C', device='cpu', writable=False)], out: Annotated[NDArray[numpy.float64], dict(shape=(None, None), order='C', device='cpu')], similarity: bool = False) -> None:
        """Fill a pre-allocated (n, n) matrix with pairwise Gower distances."""

    def calculate_matrix_xy(self, x_data: Annotated[NDArray[numpy.float64], dict(shape=(None, None), order='C', device='cpu', writable=False)], y_data: Annotated[NDArray[numpy.float64], dict(shape=(None, None), order='C', device='cpu', writable=False)], out: Annotated[NDArray[numpy.float64], dict(shape=(None, None), order='C', device='cpu')], similarity: bool = False) -> None:
        """Fill a pre-allocated (n_x, n_y) matrix with cross pairwise Gower."""

class CppConfigDataF:
    def __init__(self) -> None: ...

    @property
    def feature_types(self) -> list[str]: ...

    @feature_types.setter
    def feature_types(self, arg: Sequence[str], /) -> None: ...

    @property
    def feature_weights(self) -> Annotated[NDArray[numpy.float32], dict(shape=(None,), order='C', device='cpu', writable=False)]: ...

    @feature_weights.setter
    def feature_weights(self, arg: Annotated[NDArray[numpy.float32], dict(shape=(None,), order='C', device='cpu', writable=False)], /) -> None: ...

    @property
    def ranges(self) -> Annotated[NDArray[numpy.float32], dict(shape=(None,), order='C', device='cpu', writable=False)]: ...

    @ranges.setter
    def ranges(self, arg: Annotated[NDArray[numpy.float32], dict(shape=(None,), order='C', device='cpu', writable=False)], /) -> None: ...

    @property
    def bandwidths(self) -> Annotated[NDArray[numpy.float32], dict(shape=(None,), order='C', device='cpu', writable=False)]: ...

    @bandwidths.setter
    def bandwidths(self, arg: Annotated[NDArray[numpy.float32], dict(shape=(None,), order='C', device='cpu', writable=False)], /) -> None: ...

    @property
    def missing_strategy(self) -> str: ...

    @missing_strategy.setter
    def missing_strategy(self, arg: str, /) -> None: ...

    @property
    def scale_method(self) -> str: ...

    @scale_method.setter
    def scale_method(self, arg: str, /) -> None: ...

    @property
    def categorical_ordinal_calculation_type(self) -> str: ...

    @categorical_ordinal_calculation_type.setter
    def categorical_ordinal_calculation_type(self, arg: str, /) -> None: ...

    @property
    def conditional_distances(self) -> bool: ...

    @conditional_distances.setter
    def conditional_distances(self, arg: bool, /) -> None: ...

    @property
    def conditional_distances_threshold_coeff(self) -> int: ...

    @conditional_distances_threshold_coeff.setter
    def conditional_distances_threshold_coeff(self, arg: int, /) -> None: ...

    @property
    def discretization(self) -> str: ...

    @discretization.setter
    def discretization(self, arg: str, /) -> None: ...

    @property
    def silverman_constant(self) -> float: ...

    @silverman_constant.setter
    def silverman_constant(self, arg: float, /) -> None: ...

    @property
    def k_neighbors(self) -> int | None: ...

    @k_neighbors.setter
    def k_neighbors(self, arg: int | None) -> None: ...

    @property
    def handle_unseen_binary_asymmetric(self) -> str: ...

    @handle_unseen_binary_asymmetric.setter
    def handle_unseen_binary_asymmetric(self, arg: str, /) -> None: ...

    @property
    def handle_unseen_binary_symmetric(self) -> str: ...

    @handle_unseen_binary_symmetric.setter
    def handle_unseen_binary_symmetric(self, arg: str, /) -> None: ...

    @property
    def handle_unseen_categorical_nominal(self) -> str: ...

    @handle_unseen_categorical_nominal.setter
    def handle_unseen_categorical_nominal(self, arg: str, /) -> None: ...

    @property
    def handle_unseen_categorical_ordinal(self) -> str: ...

    @handle_unseen_categorical_ordinal.setter
    def handle_unseen_categorical_ordinal(self, arg: str, /) -> None: ...

    @property
    def out_of_range(self) -> str: ...

    @out_of_range.setter
    def out_of_range(self, arg: str, /) -> None: ...

    @property
    def skip_out_of_range_validation(self) -> bool: ...

    @skip_out_of_range_validation.setter
    def skip_out_of_range_validation(self, arg: bool, /) -> None: ...

    @property
    def categorical_ordinal_values_order(self) -> dict[int, list[str]]: ...

    @categorical_ordinal_values_order.setter
    def categorical_ordinal_values_order(self, arg: Mapping[int, Sequence[str]], /) -> None: ...

    @property
    def binary_asymmetric_value_order(self) -> dict[int, list[str]]: ...

    @binary_asymmetric_value_order.setter
    def binary_asymmetric_value_order(self, arg: Mapping[int, Sequence[str]], /) -> None: ...

    @property
    def binary_symmetric_value_order(self) -> dict[int, list[str]]: ...

    @binary_symmetric_value_order.setter
    def binary_symmetric_value_order(self, arg: Mapping[int, Sequence[str]], /) -> None: ...

    @property
    def ordinal_counts(self) -> dict[int, list[float]]: ...

    @ordinal_counts.setter
    def ordinal_counts(self, arg: Mapping[int, Sequence[float]], /) -> None: ...

class CppConfigF:
    def __init__(self) -> None: ...

    def configure_arguments(self, data: CppConfigDataF) -> None:
        """Populate the config from a ConfigData."""

    @property
    def n_features(self) -> int: ...

    @property
    def feature_weights(self) -> list[float]: ...

    @property
    def ranges(self) -> list[float]: ...

    @property
    def bandwidths(self) -> list[float]: ...

    def calculate_distance(self, x: Annotated[NDArray[numpy.float32], dict(shape=(None,), order='C', device='cpu', writable=False)], y: Annotated[NDArray[numpy.float32], dict(shape=(None,), order='C', device='cpu', writable=False)]) -> float:
        """Gower distance between two 1-D feature vectors."""

    def calculate_matrix(self, data: Annotated[NDArray[numpy.float32], dict(shape=(None, None), order='C', device='cpu', writable=False)], out: Annotated[NDArray[numpy.float32], dict(shape=(None, None), order='C', device='cpu')], similarity: bool = False) -> None:
        """Fill a pre-allocated (n, n) matrix with pairwise Gower distances."""

    def calculate_matrix_xy(self, x_data: Annotated[NDArray[numpy.float32], dict(shape=(None, None), order='C', device='cpu', writable=False)], y_data: Annotated[NDArray[numpy.float32], dict(shape=(None, None), order='C', device='cpu', writable=False)], out: Annotated[NDArray[numpy.float32], dict(shape=(None, None), order='C', device='cpu')], similarity: bool = False) -> None:
        """Fill a pre-allocated (n_x, n_y) matrix with cross pairwise Gower."""

class CppConfigDataH:
    def __init__(self) -> None: ...

    @property
    def feature_types(self) -> list[str]: ...

    @feature_types.setter
    def feature_types(self, arg: Sequence[str], /) -> None: ...

    @property
    def feature_weights(self) -> Annotated[NDArray[numpy.float16], dict(shape=(None,), order='C', device='cpu', writable=False)]: ...

    @feature_weights.setter
    def feature_weights(self, arg: Annotated[NDArray[numpy.float16], dict(shape=(None,), order='C', device='cpu', writable=False)], /) -> None: ...

    @property
    def ranges(self) -> Annotated[NDArray[numpy.float16], dict(shape=(None,), order='C', device='cpu', writable=False)]: ...

    @ranges.setter
    def ranges(self, arg: Annotated[NDArray[numpy.float16], dict(shape=(None,), order='C', device='cpu', writable=False)], /) -> None: ...

    @property
    def bandwidths(self) -> Annotated[NDArray[numpy.float16], dict(shape=(None,), order='C', device='cpu', writable=False)]: ...

    @bandwidths.setter
    def bandwidths(self, arg: Annotated[NDArray[numpy.float16], dict(shape=(None,), order='C', device='cpu', writable=False)], /) -> None: ...

    @property
    def missing_strategy(self) -> str: ...

    @missing_strategy.setter
    def missing_strategy(self, arg: str, /) -> None: ...

    @property
    def scale_method(self) -> str: ...

    @scale_method.setter
    def scale_method(self, arg: str, /) -> None: ...

    @property
    def categorical_ordinal_calculation_type(self) -> str: ...

    @categorical_ordinal_calculation_type.setter
    def categorical_ordinal_calculation_type(self, arg: str, /) -> None: ...

    @property
    def conditional_distances(self) -> bool: ...

    @conditional_distances.setter
    def conditional_distances(self, arg: bool, /) -> None: ...

    @property
    def conditional_distances_threshold_coeff(self) -> int: ...

    @conditional_distances_threshold_coeff.setter
    def conditional_distances_threshold_coeff(self, arg: int, /) -> None: ...

    @property
    def discretization(self) -> str: ...

    @discretization.setter
    def discretization(self, arg: str, /) -> None: ...

    @property
    def silverman_constant(self) -> float: ...

    @silverman_constant.setter
    def silverman_constant(self, arg: float, /) -> None: ...

    @property
    def k_neighbors(self) -> int | None: ...

    @k_neighbors.setter
    def k_neighbors(self, arg: int | None) -> None: ...

    @property
    def handle_unseen_binary_asymmetric(self) -> str: ...

    @handle_unseen_binary_asymmetric.setter
    def handle_unseen_binary_asymmetric(self, arg: str, /) -> None: ...

    @property
    def handle_unseen_binary_symmetric(self) -> str: ...

    @handle_unseen_binary_symmetric.setter
    def handle_unseen_binary_symmetric(self, arg: str, /) -> None: ...

    @property
    def handle_unseen_categorical_nominal(self) -> str: ...

    @handle_unseen_categorical_nominal.setter
    def handle_unseen_categorical_nominal(self, arg: str, /) -> None: ...

    @property
    def handle_unseen_categorical_ordinal(self) -> str: ...

    @handle_unseen_categorical_ordinal.setter
    def handle_unseen_categorical_ordinal(self, arg: str, /) -> None: ...

    @property
    def out_of_range(self) -> str: ...

    @out_of_range.setter
    def out_of_range(self, arg: str, /) -> None: ...

    @property
    def skip_out_of_range_validation(self) -> bool: ...

    @skip_out_of_range_validation.setter
    def skip_out_of_range_validation(self, arg: bool, /) -> None: ...

    @property
    def categorical_ordinal_values_order(self) -> dict[int, list[str]]: ...

    @categorical_ordinal_values_order.setter
    def categorical_ordinal_values_order(self, arg: Mapping[int, Sequence[str]], /) -> None: ...

    @property
    def binary_asymmetric_value_order(self) -> dict[int, list[str]]: ...

    @binary_asymmetric_value_order.setter
    def binary_asymmetric_value_order(self, arg: Mapping[int, Sequence[str]], /) -> None: ...

    @property
    def binary_symmetric_value_order(self) -> dict[int, list[str]]: ...

    @binary_symmetric_value_order.setter
    def binary_symmetric_value_order(self, arg: Mapping[int, Sequence[str]], /) -> None: ...

    @property
    def ordinal_counts(self) -> dict[int, list[float]]: ...

    @ordinal_counts.setter
    def ordinal_counts(self, arg: Mapping[int, Sequence[float]], /) -> None: ...

class CppConfigH:
    def __init__(self) -> None: ...

    def configure_arguments(self, data: CppConfigDataH) -> None:
        """Populate the config from a ConfigData."""

    @property
    def n_features(self) -> int: ...

    @property
    def feature_weights(self) -> list[float]: ...

    @property
    def ranges(self) -> list[float]: ...

    @property
    def bandwidths(self) -> list[float]: ...

    def calculate_distance(self, x: Annotated[NDArray[numpy.float16], dict(shape=(None,), order='C', device='cpu', writable=False)], y: Annotated[NDArray[numpy.float16], dict(shape=(None,), order='C', device='cpu', writable=False)]) -> float:
        """Gower distance between two 1-D feature vectors."""

    def calculate_matrix(self, data: Annotated[NDArray[numpy.float16], dict(shape=(None, None), order='C', device='cpu', writable=False)], out: Annotated[NDArray[numpy.float16], dict(shape=(None, None), order='C', device='cpu')], similarity: bool = False) -> None:
        """Fill a pre-allocated (n, n) matrix with pairwise Gower distances."""

    def calculate_matrix_xy(self, x_data: Annotated[NDArray[numpy.float16], dict(shape=(None, None), order='C', device='cpu', writable=False)], y_data: Annotated[NDArray[numpy.float16], dict(shape=(None, None), order='C', device='cpu', writable=False)], out: Annotated[NDArray[numpy.float16], dict(shape=(None, None), order='C', device='cpu')], similarity: bool = False) -> None:
        """Fill a pre-allocated (n_x, n_y) matrix with cross pairwise Gower."""
