name: Tests & checks

on:
  push:
    branches:
      - main
      - refactor_newapi
  workflow_dispatch:

jobs:
  ci:
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - uses: actions/cache@v4
        name: Define a venv cache
        with:
          path: ./.venv
          key: ${{ matrix.os }}-venv-${{ hashFiles('**/uv.lock') }}

      - name: Install the project dependencies
        run: uv sync

      - name: Run tests with pytest
        run: uv run pytest tests/gower_api
  
  comparison_with_R:
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.10"]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v6
  
      - uses: actions/cache@v4
        name: Define a venv cache
        with:
          path: ./.venv
          key: ${{ matrix.os }}-venv-${{ hashFiles('**/uv.lock') }}

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.5.1'
          
      - name: Install R packages
        run: |
          Rscript -e "if(!require(cluster)) install.packages('cluster')"
          Rscript -e "if(!require(drat)) install.packages('drat')"
          Rscript -e "drat::addRepo('markvanderloo')"
          Rscript -e "install.packages('gower',type='source')"

      - name: Install the project dependencies
        run: uv sync

      - name: Install rpy2 package
        run: uv run pip install rpy2

      - name: Run tests with pytest
        run: |
            uv run pytest tests/R_comparison